/**
 * Store Event-name constants
 */
export const ROUTER_CHANGED = 'EVENT:$ROUTER_CHANGED';

export const USERS_RECEIVED = 'EVENT:USERS_RECEIVED';
export const REPOS_RECEIVED = 'EVENT:REPOS_RECEIVED';
export const PAGINATION_UPDATED = 'EVENT:PAGINATION_UPDATED';
export const RECALCULATE_AVAILABLE_PAGES = 'EVENT:RECALCULATE_AVAILABLE_PAGES';
