const USERS_RECEIVED = 'EVENT:USERS_RECEIVED';
const REPOS_RECEIVED = 'EVENT:REPOS_RECEIVED';
const PAGINATION_UPDATED = 'EVENT:PAGINATION_UPDATED';
const RECALCULATE_AVAILABLE_PAGES = 'EVENT:RECALCULATE_AVAILABLE_PAGES';
const ROUTER_CHANGED = '$ROUTER_CHANGED';

export default {
  USERS_RECEIVED,
  REPOS_RECEIVED,
  PAGINATION_UPDATED,
  RECALCULATE_AVAILABLE_PAGES,
  ROUTER_CHANGED
};
